on:
  pull_request:
  push:
    branches: master
    tags: 'v*'

name: Build and Release

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [macos-latest, windows-latest, ubuntu-latest]
        os: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: yarn install
        run: |
          yarn install --frozen-lockfile --network-timeout 300000

      - name: yarn build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn package
          #yarn lint
          #yarn tsc
          #yarn test

  release:
    needs: build
    name: Release
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}
      - name: Release
        uses: softprops/action-gh-release@latest
        with:
          name: Release ${{ github.ref }}
          body: ${{ steps.Changelog.outputs.changelog }}
          draft: true
          prerelease: false
          fail_on_unmatched_files: true
          files: |
            release/YoutubePlayer*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
