on:
  workflow_run:
    workflows: ['Build']
    types:
      - completed

name: Create Release

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        env:
          REPO: ${{ github.repository }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: true
          prerelease: false
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.Changelog.outputs.changelog }}
          files: |
            *-latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
